export const ORDERREQUEST="ORDERREQUEST"
export const ORDERFAIL="ORDERFAIL"

export const POSTORDERSUCCESS="POSTORDERSUCCESS"
export const GETORDERSUCCESS="GETORDERSUCCESS"
export const DELETEORDERSUCCESS="DELETETORDERSUCCESS"